---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-lease-r
  annotations:
    argocd.argoproj.io/sync-wave: '2'
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - ''
    resources:
      - secrets
      - pods
      - services
      - configmaps
    verbs:
      - get
      - create
      - update
      - list
      - watch
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
      - certificaterequests
      - clusterissuers
      - issuers
    verbs:
      - list
      - watch
  - apiGroups:
      - acme.cert-manager.io
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - list
      - watch
