---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-lease-rb
  annotations:
    argocd.argoproj.io/sync-wave: '3'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-lease-r
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: openshift-cert-manager
