---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-openshift-routes
  namespace: openshift-cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  labels:
    app.kubernetes.io/name: cert-manager-openshift-routes
    app.kubernetes.io/version: '0.1.3'
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: openshift-cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager-openshift-routes
      app.kubernetes.io/version: '0.1.3'
      app.kubernetes.io/component: controller
      app.kubernetes.io/part-of: openshift-cert-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cert-manager-openshift-routes
        app.kubernetes.io/version: '0.1.3'
        app.kubernetes.io/component: controller
        app.kubernetes.io/part-of: openshift-cert-manager
    spec:
      serviceAccountName: cert-manager-openshift-routes
      automountServiceAccountToken: true
      containers:
        - name: cert-manager-openshift-routes
          image: 'ghcr.io/cert-manager/cert-manager-openshift-routes:0.1.3'
          args:
            - -v=5
            - '--leader-election-namespace=openshift-cert-manager'
          ports:
            - containerPort: 6060
              name: readiness
              protocol: TCP
            - containerPort: 9042
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              port: readiness
              path: '/readyz'
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3
