---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  name: cert-manager-openshift-routes
  namespace: openshift-cert-manager
automountServiceAccountToken: false
