apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
resources:
  - operatorgroup.yaml
  - subscription.yaml
  - cluster.yaml
  - cm-openshift-deployment.yaml
  - cm-openshift-routes-clusterrole.yaml
  - cm-openshift-routes-crb.yaml
  - cm-openshift-routes-sa.yaml
  - cm-lease-crb.yaml
  - cm-lease-r.yaml
